chain:
    bech32_prefix: p_bech32_prefix
    modules:
        - modules
        - messages
        - auth
        - bank
        - consensus
        - gov
        - pricefeed
        - slashing
        - staking
        - distribution
        - actions
node:
    type: remote
    config:
        rpc:
            client_name: juno
            address: http://p_rpc_addr
            max_connections: 20
        grpc:
            address: p_grpc_addr
            insecure: true
parsing:
    workers: 1
    start_height: 1
    average_block_time: 5s
    listen_new_blocks: true
    parse_old_blocks: true
    parse_genesis: true
database:
    url: postgresql://p_db_user:p_db_pass@localhost:p_db_port/p_db_name?sslmode=disable&search_path=public
    max_open_connections: 1
    max_idle_connections: 1
    partition_size: 100000
    partition_batch: 1000
logging:
    level: debug
    format: text
actions:
    host: 127.0.0.1
    port: 3000
pruning:
    keep_recent: 100
    keep_every: 500
    interval: 10
telemetry:
    port: 5000
pricefeed:
    tokens:
        - name: p_token_denom
          units:
            - denom: p_token_min_denom
              exponent: 0
            - denom: p_token_denom
              exponent: p_denom_exponent
              price_id: evmos
