#!/bin/bash

if [ "$CHAIN_NO" = "1" ]; then
    export CHAIN_ID="$CHAIN_1_ID"
    export GIT_BRANCH="$CHAIN_1_GIT_REPO_BRANCH"
    export GIT_REPO="$CHAIN_1_GIT_REPO"
    export DAEMON_BINARY_NAME="$CHAIN_1_DAEMON_BINARY_NAME"
    export EVMOS_CLAIM_MODULE_ACCOUNT="$EVMOS_CHAIN_1_CLAIM_MODULE_ACCOUNT"
    export EVMOS_DENOM_EXPONENT=$CHAIN_1_DENOM_EXPONENT
    export EVMOS_GAS_DENOM_EXPONENT=$EVMOS_CHAIN_1_GAS_DENOM_EXPONENT
    export DENOM_SYMBOL="$CHAIN_1_DENOM_SYMBOL"
    export MIN_DENOM_SYMBOL="$CHAIN_1_MIN_DENOM_SYMBOL"
    export GAS_DENOM_SYMBOL="$CHAIN_1_GAS_DENOM_SYMBOL"
    export VAL_1_SEED="$VAL_1_CHAIN_1_SEED"
    export VAL_1_PRIVATE_KEY="$VAL_1_CHAIN_1_PRIVATE_KEY"
    export VAL_2_SEED="$VAL_2_CHAIN_1_SEED"
    export VAL_2_PRIVATE_KEY="$VAL_2_CHAIN_1_PRIVATE_KEY"
    export VAL_3_SEED="$VAL_3_CHAIN_1_SEED"
    export VAL_3_PRIVATE_KEY="$VAL_3_CHAIN_1_PRIVATE_KEY"
    export VALIDATOR_IMPORT_TYPE="$CHAIN_1_VALIDATOR_IMPORT_TYPE"
    export ACCOUNT_PREFIX="$CHAIN_1_ACCOUNT_PREFIX"
elif [ "$CHAIN_NO" = "2" ]; then
    export CHAIN_ID="$CHAIN_2_ID"
    export GIT_BRANCH="$CHAIN_2_GIT_REPO_BRANCH"
    export GIT_REPO="$CHAIN_2_GIT_REPO"
    export DAEMON_BINARY_NAME="$CHAIN_2_DAEMON_BINARY_NAME"
    export EVMOS_CLAIM_MODULE_ACCOUNT="$EVMOS_CHAIN_2_CLAIM_MODULE_ACCOUNT"
    export EVMOS_DENOM_EXPONENT=$CHAIN_2_DENOM_EXPONENT
    export EVMOS_GAS_DENOM_EXPONENT=$EVMOS_CHAIN_2_GAS_DENOM_EXPONENT
    export DENOM_SYMBOL="$CHAIN_2_DENOM_SYMBOL"
    export MIN_DENOM_SYMBOL="$CHAIN_2_MIN_DENOM_SYMBOL"
    export GAS_DENOM_SYMBOL="$CHAIN_2_GAS_DENOM_SYMBOL"
    export VAL_1_SEED="$VAL_1_CHAIN_2_SEED"
    export VAL_1_PRIVATE_KEY="$VAL_1_CHAIN_2_PRIVATE_KEY"
    export VAL_2_SEED="$VAL_2_CHAIN_2_SEED"
    export VAL_2_PRIVATE_KEY="$VAL_2_CHAIN_2_PRIVATE_KEY"
    export VAL_3_SEED="$VAL_3_CHAIN_2_SEED"
    export VAL_3_PRIVATE_KEY="$VAL_3_CHAIN_2_PRIVATE_KEY"
    export VALIDATOR_IMPORT_TYPE="$CHAIN_2_VALIDATOR_IMPORT_TYPE"
    export ACCOUNT_PREFIX="$CHAIN_2_ACCOUNT_PREFIX"
fi

export EVMOS_SOURCE_DIR="./source-code-$DENOM_SYMBOL-$GIT_BRANCH"
export EVMOS_CHAINNAME=$(echo $DENOM_SYMBOL | tr '[:lower:]' '[:upper:]')
export VAL_HOME_PREFIX=".evmosd$CHAIN_NO"

echo "Creating $ACCOUNT_PREFIX network with chain id $CHAIN_ID"
echo "- Account prefix: $ACCOUNT_PREFIX"
echo "- Denom symbol: $DENOM_SYMBOL ($EVMOS_DENOM_EXPONENT digits unit: $MIN_DENOM_SYMBOL, $EVMOS_GAS_DENOM_EXPONENT digits gas unit: $GAS_DENOM_SYMBOL)"
echo "- Source code on repo: $GIT_REPO"
echo "- Source code on branch: $GIT_BRANCH"
echo "- Download source code to dir: $EVMOS_SOURCE_DIR"
echo "- Expect deamon binary name: $DAEMON_BINARY_NAME"
echo "- Claim module account: $EVMOS_CLAIM_MODULE_ACCOUNT"