version: "3"
networks:
  vtevmosnw[p_chain_no]:
    driver: bridge
services:
  vtevmos[p_chain_no]0:
    container_name: vtevmos[p_chain_no]0
    ports:
      - "[p_8545]:8545"
      - "[p_26657]:26657"
      - "[p_1317]:1317"
      - "[p_9090]:9090"
      - "[p_26656]:26656"
    networks:
      - vtevmosnw[p_chain_no]
    environment:
      - NODE=0
    restart: always
    image: [p_image_prefix][p_chain_no]
  vtevmos[p_chain_no]1:
    container_name: vtevmos[p_chain_no]1
    networks:
      - vtevmosnw[p_chain_no]
    environment:
      - NODE=1
    depends_on:
      - vtevmos[p_chain_no]0
    restart: always
    image: [p_image_prefix][p_chain_no]
  vtevmos[p_chain_no]2:
    container_name: vtevmos[p_chain_no]2
    networks:
      - vtevmosnw[p_chain_no]
    environment:
      - NODE=2
    depends_on:
      - vtevmos[p_chain_no]0
    restart: always
    image: [p_image_prefix][p_chain_no]