#!/bin/bash

source ../env.sh

GENSIS_JSON_ORIGIN="genesis.json"
CONFIG_TOML_ORIGIN="config.toml"
if [ ! -f $GENSIS_JSON_ORIGIN ]; then
	echo "Missing file $GENSIS_JSON_ORIGIN"
	echo "Copy the original $GENSIS_JSON_ORIGIN file which was generated by the first node and paste it into this dir"
	exit 1
fi
