chain:
    bech32_prefix: evmos
    modules:
        - modules
        - messages
        - auth
        - bank
        - consensus
        - gov
        - mint
        - pricefeed
        - slashing
        - staking
        - distribution
        - actions
node:
    type: remote
    config:
        rpc:
            client_name: juno
            address: http://evmosc1.mytwdns.com:26657
            max_connections: 20
        grpc:
            address: evmosc1.mytwdns.com:9090
            insecure: true
parsing:
    workers: 1
    listen_new_blocks: true
    parse_old_blocks: true
    parse_genesis: true
    start_height: 1
    average_block_time: 5s
database:
    name: bdjuno
    host: 0.0.0.0
    port: 5432
    user: bdjuno
    password: 6N4QtiFYMt7h97uazrWTckmMvFZW9Ije
    schema: public
    max_open_connections: 1
    max_idle_connections: 1
    partition_size: 100000
    partition_batch: 1000
logging:
    level: debug
    format: text
pruning:
    keep_recent: 100
    keep_every: 500
    interval: 10
telemetry:
    port: 5000
pricefeed:
    tokens:
        - name: EVMOS
          units:
            - denom: aevmos
              exponent: 0
            - denom: evmos
              exponent: 18
              price_id: evmos
actions:
    port: 3000
